name: CI
on:
  push:

permissions:
  id-token: write
  contents: read
  pull-requests: read
env:
  GO_VERSION: 1.23.2
jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-server
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Check format
        run: go fmt ./...
  go-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-server
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build test
        run: go build main.go
