name: CI
on:
  push:

permissions:
  id-token: write
  contents: read
  pull-requests: read
env:
  GO_VERSION: 1.23.2
jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - run: go mod download
      - name: Check format
        run: go fmt ./...
  go-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - run: go mod download
      - name: Build test
        run: go build main.go
