name: Build App for Production
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  prd-build-backend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository }}:1.0.${{ github.run_number }}
            ghcr.io/${{ github.repository }}:latest
          path: "."
          cache-registry: ghcr.io/${{ github.repository }}:buildcache
