name: Build App for Staging
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  stg-build-backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment: staging # 管理者の承認を必要とする
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}:stg-${{ github.sha }}-${{ github.run_number }}
          path: "."
          cache-registry: ghcr.io/${{ github.repository }}:buildcache
  stg-build-backend-main:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}:stg-${{ github.sha }}-${{ github.run_number }}
          path: "."
          cache-registry: ghcr.io/${{ github.repository }}:buildcache
